@extends('layouts.Frontend.app')

@section('title')
    Profile Sekolah
@endsection

@section('content')
    @section('about')
        <div class="container">
            @if ($profile)
                <div style="margin-top: 5%; margin-bottom:3%"><center>
                    <img src="{{asset('storage/images/profileSekolah/' .$profile->image)}}" class="img-responsive" style="height:60%; width:60%; object-fit:cover"></center>
                </div>
                <h2 class="title-center">{{$profile->title}}</h2>
                <p class="sub-title-full-width-justify" align="justify">&nbsp;&nbsp;&nbsp;{{$profile->content}}</style></p>
               <!-- <p align="justify">&nbsp;&nbsp;&nbsp; SMP Negeri  21 Kota Bengkulu terletak di kota tepatnya di Kelurahan Panorama, Singaran Pati, Kota Bengkulu, dengan luas tanah ± 13,615  m2. SMP Negeri  21 Kota Bengkulu terletak pada lokasi sekolah yang strategis dan nyaman,  berada tidak jauh dari pusat kota tetapi nyaman karena berada bukan di pemukiman padat penduduk. Sekolah berada di pinggir jala raya dan mudah diakses semua kendaraan dari arah kota. Letak strategis sekolah sering dimanfaatkan untuk acara pendidikan tingkat kota seperti workshop dan berbagai lomba antar sekolah, sehingga dampak positif bagi sekolah dapat dirasakan. 
SMP Negeri  21 Kota Bengkulu berorientasi untuk mengembangkan diri menjadi sekolah alternative untuk semua kalangan dengan bermodalkan mutu yang terjamin dan selalu mengembangkan diri  sesuai Standar Nasional Pendidikan.
SMP Negeri  21 Kota Bengkulu telah disusun dengan melibatkan warga sekolah , komite dan melibatkan stakeholder yang lain.
</p>
<p align="justify">&nbsp;&nbsp;&nbsp; Pengembangan Silabus dan RPP  mata pelajaran  melalui MGMP yang diikuti semua guru mapel di SMP Negeri  21 Kota Bengkulu dengan tahapan melakukan pemetaan Standar Kompetensi, kompetensi dasar dan evaluasi dari pelaksanaan pembelajaran.</p>
<p align="justify">&nbsp;&nbsp;&nbsp; Kekuatan sekolah berada pada input siswa, tenaga pendidik dan tenaga kependidikan, manajemen sekolah dan partisipasi orang tua / masyarakat. Siswa baru berasal dari berbagai sekolah dasar yang tersebar di sekitar 3 kecamatan, yaitu Kecamatan Singaran Pati, Kec Ratu Agung dan Kec. Gading Cempaka. Jumlah pendaftar yang selalu melebihi PAGU bagi sekolah yang berdiri tahun 2002 menjadi modal tersendiri untuk dikembangkan dan dicetak menjadi lulusan yang berkompetensi serta berkualitas. Jumlah peserta didik pada tahun pelajaran 2014/2015 sebanyak 595 orang, yang terbagi dalam 21 rombongan belajar. Kelas VII terdiri dari 7 rombel,dengan rata-rata tiap kelas terdiri dari 30 siswa. Kelas VIII sebanyak 7 rombel dengan rata-rata tiap kelas terdiri dari 27 siswa, kelas IX sebanyak 7 rombel dengan rata-rata tiap kelas terdiri dari 28 siswa. Seluruh siswa masuk pagi. Jumlah Peserta tahun Pelajaran 2020/2021 sebanyak 670, yang terbagi dalam 22 rombel belajar, kelas VII dari 8 rombel, dengan rata-rata terdiri 30 siswa. Kelas VIII sebanyak 7 rombel dengan rata-rata 30 siswa, kelas IX sebanyak 7 rombel dengan rata-rata tiap kelas terdiri 30 siswa. Jumlah Peserta tahun ajaran 2022/2023 sebanyak 593, yang terdiri dalam 20 rombel. Kelas VII 6 Rombel, kelas VIII 6 rombel, Kelas IX 8 rombel dengan rata-rata 30 siswa.</p>
<p align="justify">&nbsp;&nbsp;&nbsp; Tenaga pendidik dan tenaga kependidikan berjumlah 41 orang mayoritas berusia muda (rata-rata berusia 25 – 45 tahun), kualifikasi S2 (15 %), S1 (80%) dan kualifikasi D3 (5 %). Dari 41 tenaga pendidik, 1 orang menjadi tutor tingkat propinsi untuk mata pelajaran PAI, 2 orang menjadi tutor tingkat Nasional mata pelajaran Seni Budaya, serta seluruh pendidik ( 100 %) telah mengikuti berbagai diklat dan pelatihan KTSP untuk mata pelajaran masing-masing. Beberapa guru mata pelajaran IPA, Matematika, Bahasa Indonesia, dan Bahasa Inggris secara aktif telah mengikuti kegiatan BERMUTU (Better Education through Reformed Management and Universal Teacher Upgrading) di MGMP tingkat kota. Sedangkan semua guru mata pelajaran tengah mengikuti program peningkatan mutu melalui block grant PTK Dikdas. Hal ini menjadi modal tersendiri bagi sekolah untuk meningkatkan mutu pendidikan utamanya mutu pembelajaran di kelas.</p>
<p align="justify">&nbsp;&nbsp;&nbsp; Peluang lain bahwa SMP Negeri 21 Kota Bengkulu berdiri tahun 2002,  tetapi telah menorehkan banyak prestasi di tingkat kabupaten dan propinsi selama 2013/2014: yakni,  Juara 1 lomba Futsal, juara 1 lomba baca puisi,  juara umum pramuka Tingkat Propinsi Di UNIB, Juara Umum Pramuka tingkat Kota di SMPN 2 Kota Bengkulu, Juara Umum Lomba Keterampilan Pramuka Kwarcab Kota Bengkulu. Sekolah juga mewakili Kabupaten/kota dalam beberapa lomba olahraga dan seni ke tingkat propinsi. Antara lain pertandingan Bola Voly dan Futsal.</p>
<p align="justify">&nbsp;&nbsp;&nbsp; Sarana yang ada di sekolah kami adalah 21 ruang kelas, 1 ruang guru, 1 ruang kepala sekolah, 1 ruang kurikulum, 1 ruang tata usaha, 1 ruang perpustakaan, 1 ruang laboratorium IPA, 1 ruang laboratorium Komputer, 1 ruang labor Bahasa ruang serba guna (aula) 12 kamar mandi siswa, 1 kamar mandi guru, 1 kamar mandi  Kepala sekolah, 1 ruang kopsis,1 ruang UKS,1 ruang BK, 2 kamar gudang,  1 ruang OSIS, mushola, lapangan upacara, lapangan Olah raga, alat musik tradisonal dan modern dan tempat parkir guru/ siswa yang memadai. Manajemen sekolah berorientasi pada MBS (Manajemen Berbasis Sekolah). Kepala sekolah sebagai leader mampu menggerakkan segenap warga sekolah untuk berperan aktif dan nyata guna kepentingan pendidikan. Pembagian tugas yang jelas, program kerja terarah, optimalisasi peran dan fungsi masing-masing bagian yang selalu disupervisi dan dievaluasi membantu sekolah dalam meningkatkan kinerja dan prestasi sekolah.</p>
<p align="justify">&nbsp;&nbsp;&nbsp; Keberadaan Dunia Usaha (DU) di SMPN 21 Kota Bengkulu ditandai dengan perjanjian kerjasama dengan Telkom Speedy, Bimbingan belajar GO , dan beberapa penerbit menjadi mitra sekolah dalam segala kegiatan.
Partisipasi positif masyarakat (orang tua siswa) yang diwadahi komite sekolah telah memberikan sumbangan bagi terciptanya mutu pendidikan yang lebih baik lagi. Dengan menginformasikan berbagai program sekolah dengan komite telah muncul sinergi antara sekolah dan orang tua siswa sehingga pelaksanaan kegiatan sekolah menjadi lebih mudah dan optimal dilaksanakan.
Sejalan dengan cepatnya arus teknologi, jaringan wi fi sudah tersedia di ruang laboratorium komputer. Sehingga pembelajaran berbasis website (Web Teaching Materials) telah dapat dilaksanakan dengan optimal.</p>
<p align="justify">&nbsp;&nbsp;&nbsp; Kelemahan SMP Negeri 21 Kota Bengkulu terletak pada kurang lengkapnya sarana dan prasarana sekolah. Sekolah memiliki laboratorium IPA tetapi alat-alat dan bahan praktikum tidak memadai sehingga penggunaannya untuk praktikum menjadi terbatas. Sekolah telah mempunyai laboratorium komputer tapi belum memiliki unit komputer yang memadai untuk melayani siswa. Sekolah telah memiliki seperangkat alat komputer untuk laboratorium bahasa tetapi belum memiliki gedung laboratorium sendiri. Sehingga yang terjadi di lapangan adalah seluruh perangkat laboratorium bahasa digunakan untuk pembelajaran TIK keseluruhan. Pembelajaran bahasa masih dilaksanakan di ruang kelas. Sekolah belum memiliki Sanggar Pramuka, ruang kesenian, dan lapangan untuk bidang olahraga tertentu yaitu, badminton, Tidak adanya sarana ini menyebabkan fungsi dan pelaksanaan kegiatan pendidikan di SMP Negeri 21 Kota Bengkulu sering tidak berjalan dengan maksimal. Sebagai sekolah rintisan SSN, sekolah baru memiliki 2 unit komputer di ruang TU, 1 unit komputer di ruang guru, 1 unit komputer di ruang Kurikulum, dan  5 laptop, 2 unit AC di ruang Lab Bahasa, 1 unit sound system.  Hal ini tentu saja menghambat proses pembelajaran dan hasilnya tidak maksimal.</p>
<p align="justify">&nbsp;&nbsp;&nbsp; Ancaman sekolah umumnya akibat dari globalisasi yang belum berhasil difilter secara cermat sehingga menghadirkan budaya yang tidak sesuai dengan kebiasaan, adat, dan nilai-nilai budi pekerti luhur. Dampak televisi memperparah keadaan ini dengan mencontohkan perilaku yang tidak sedap dipandang mata berupa pergaulan bebas, pakaian tidak pantas, potongan rambut yang tidak rapi, gemerlap komersialisme, hedonisme dan impian semu yang menghanyutkan. Kebanyakan remaja kita kemudian kehilangan pegangan dalam menjalani hidup dan tidak punya arah yang jelas dalam menghadapi tantangan hidup yang semakin kompetitif. Untuk itu peran sekolah dan orang tua siswa akan lebih diintensifkan untuk mengendalikan dan  memberi teladan perilaku yang bermoral baik dan sesuai dengan budi pekerti luhur.</p>
<p align="justify">&nbsp;&nbsp;&nbsp; APBS dan RKA di SMPN 21 Kota Bengkulu disusun bersama-sama dengan Komite Sekolah dan mempertimbangkan kemampuan ekonomi orang tua siswa.
Pelaksanaan penilaian yang dilakukan di SMPN 21 Kota Bengkulu lebih menekankan pada proses dengan memberi bobot terbesar pada nilai ulangan harian dari pada nilai akhir semester.
</p>-->


            @else
                <img src="{{asset('Assets/Frontend/img/empty.svg')}}" class="img-responsive" style="object-fit:cover; margin-top:5% !important; display: block;
            margin: 0 auto;">
            @endif
        </div>
    @endsection

    {{-- Guru --}}
    @section('guru')
        @include('frontend.content.guru')
    @endsection
@endsection
